"""create summaries table

Revision ID: 705744c44ac9
Revises: b663b249c42d
Create Date: 2026-08-09 21:48:09.633465
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '705744c44ac9'
down_revision: Union[str, None] = 'b663b249c42d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summaries',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('summary_type', sa.Enum('short', 'detailed', name='summary_type'), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'complete', 'failed', name='summary_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summaries_status'), 'summaries', ['status'], unique=False)
    op.create_index(op.f('ix_summaries_summary_type'), 'summaries', ['summary_type'], unique=False)
    op.create_index(op.f('ix_summaries_video_id'), 'summaries', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summaries_video_id'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_summary_type'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_status'), table_name='summaries')
    op.drop_table('summaries')
    # ### end Alembic commands ###
