"""create transcripts table

Revision ID: b663b249c42d
Revises: 7a2f9182ac47
Create Date: 2026-08-07 22:41:48.691709
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b663b249c42d'
down_revision: Union[str, None] = '7a2f9182ac47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcripts',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'complete', 'failed', name='transcript_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_language'), 'transcripts', ['language'], unique=False)
    op.create_index(op.f('ix_transcripts_status'), 'transcripts', ['status'], unique=False)
    op.create_index(op.f('ix_transcripts_video_id'), 'transcripts', ['video_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_video_id'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_status'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_language'), table_name='transcripts')
    op.drop_table('transcripts')
    # ### end Alembic commands ###
