"""add transcript segments and key moments tables

Revision ID: c458d9b298e9
Revises: 705744c44ac9
Create Date: 2026-08-12 09:00:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c458d9b298e9'
down_revision: Union[str, None] = '705744c44ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('segments', sa.JSON(), nullable=True))

    op.create_table(
        'key_moment_sets',
        sa.Column('video_id', sa.UUID(), nullable=False),
        sa.Column('status', sa.Enum('pending', 'processing', 'complete', 'failed', name='key_moment_set_status'), nullable=False),
        sa.Column('model_name', sa.String(length=100), nullable=True),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_moment_sets_status'), 'key_moment_sets', ['status'], unique=False)
    op.create_index(op.f('ix_key_moment_sets_video_id'), 'key_moment_sets', ['video_id'], unique=True)

    op.create_table(
        'key_moments',
        sa.Column('set_id', sa.UUID(), nullable=False),
        sa.Column('start_time', sa.Float(), nullable=False),
        sa.Column('end_time', sa.Float(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('type', sa.Enum('highlight', 'chapter', 'important', name='key_moment_type'), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['set_id'], ['key_moment_sets.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_moments_set_id'), 'key_moments', ['set_id'], unique=False)
    op.create_index(op.f('ix_key_moments_type'), 'key_moments', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_key_moments_type'), table_name='key_moments')
    op.drop_index(op.f('ix_key_moments_set_id'), table_name='key_moments')
    op.drop_table('key_moments')

    op.drop_index(op.f('ix_key_moment_sets_video_id'), table_name='key_moment_sets')
    op.drop_index(op.f('ix_key_moment_sets_status'), table_name='key_moment_sets')
    op.drop_table('key_moment_sets')

    op.drop_column('transcripts', 'segments')
    # ### end Alembic commands ###
