import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
const API = import.meta.env.VITE_API_URL || 'http://localhost:8000/api';
const roles = ['creator', 'educator', 'learner', 'admin'];
function App() {
  const [token, setToken] = useState(localStorage.getItem('clipmind_token'));
  const [user, setUser] = useState(JSON.parse(localStorage.getItem('clipmind_user') || 'null'));
  const [mode, setMode] = useState('login'), [videos, setVideos] = useState([]), [selected, setSelected] = useState(null);
  const [transcript, setTranscript] = useState(null), [summaries, setSummaries] = useState([]), [message, setMessage] = useState(''), [busy, setBusy] = useState(false);
  const headers = token ? { Authorization: `Bearer ${token}` } : {};
  async function request(path, options = {}) { const response = await fetch(`${API}${path}`, {...options, headers:{...headers,...(options.headers||{})}}); const data=response.status===204?null:await response.json(); if(!response.ok) throw new Error(data.detail||'Something went wrong'); return data; }
  async function loadVideos(){if(token)setVideos(await request('/videos'));}
  useEffect(()=>{loadVideos().catch(e=>setMessage(e.message));},[token]);
  async function authenticate(e){e.preventDefault();setBusy(true);try{const data=await request(`/auth/${mode}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});localStorage.setItem('clipmind_token',data.access_token);localStorage.setItem('clipmind_user',JSON.stringify(data.user));setToken(data.access_token);setUser(data.user);}catch(e){setMessage(e.message)}finally{setBusy(false)}}
  async function upload(e){e.preventDefault();const uploadForm=e.currentTarget;const file=uploadForm.video.files[0];if(!file)return;setBusy(true);try{const form=new FormData();form.append('file',file);await request('/videos/upload',{method:'POST',body:form});uploadForm.reset();await loadVideos();setMessage('Upload received.')}catch(e){setMessage(e.message)}finally{setBusy(false)}}
  async function openVideo(video){setSelected(video);setTranscript(null);setSummaries([]);try{setTranscript(await request(`/videos/${video.id}/transcript`))}catch(e){if(!e.message.includes('No transcript'))setMessage(e.message)}try{setSummaries(await request(`/videos/${video.id}/summaries`))}catch(e){setMessage(e.message)}}
  async function createTranscript(){setBusy(true);try{await request(`/videos/${selected.id}/transcript`,{method:'POST'});setTranscript({status:'processing',content:''});setMessage('Whisper is processing. Refresh in a moment.')}catch(e){setMessage(e.message)}finally{setBusy(false)}}
  async function refreshTranscript(){try{setTranscript(await request(`/videos/${selected.id}/transcript`));setSummaries(await request(`/videos/${selected.id}/summaries`))}catch(e){setMessage(e.message)}}
  async function saveTranscript(e){e.preventDefault();setBusy(true);try{setTranscript(await request(`/videos/${selected.id}/transcript`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:new FormData(e.currentTarget).get('content')})}));setMessage('Transcript saved.')}catch(e){setMessage(e.message)}finally{setBusy(false)}}
  async function createSummary(summary_type){setBusy(true);try{const result=await request(`/videos/${selected.id}/summaries`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({summary_type})});setSummaries(current=>[...current.filter(s=>s.summary_type!==summary_type),result])}catch(e){setMessage(e.message)}finally{setBusy(false)}}
  async function remove(id){if(!confirm('Remove this video?'))return;try{await request(`/videos/${id}`,{method:'DELETE'});if(selected?.id===id)setSelected(null);await loadVideos()}catch(e){setMessage(e.message)}}
  function logout(){localStorage.clear();setToken(null);setUser(null);setVideos([]);setSelected(null)}
  if(!user)return <main className="auth"><section><p className="eyebrow">WEEKS 1-4 / CLIPMIND AI</p><h1>ClipMind <em>AI</em></h1><p className="lead">Upload videos, generate transcripts, and create concise summaries.</p></section><section className="panel"><div className="tabs"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Sign in</button><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Create account</button></div><form onSubmit={authenticate}><label>Email<input name="email" type="email" required/></label>{mode==='register'&&<><label>Name<input name="name" minLength="2" required/></label><label>Role<select name="role">{roles.map(r=><option key={r}>{r}</option>)}</select></label></>}<label>Password<input name="password" type="password" minLength="8" required/></label><button className="primary" disabled={busy}>{busy?'Please wait...':mode==='login'?'Sign in':'Create account'}</button></form>{message&&<p className="notice">{message}</p>}</section></main>;
  const canEdit=selected&&(user.role==='admin'||selected.owner_id===user.id),canUpload=['creator','educator','admin'].includes(user.role);
  return <main className="dashboard"><header><div><p className="eyebrow">CLIPMIND AI / WEEKS 1-4</p><h1>Video workspace</h1></div><div className="account"><span>{user.name} / {user.role}</span><button onClick={logout}>Sign out</button></div></header><p className="notice">{message}</p>{canUpload&&<section className="upload panel"><div><h2>Bring in a video</h2><p>Upload a video to begin the FFmpeg and Whisper workflow.</p></div><form onSubmit={upload}><input name="video" type="file" accept="video/*,.mkv" required/><button className="primary" disabled={busy}>Upload video</button></form></section>}<section><div className="section-title"><h2>{user.role==='learner'?'Available videos':'Your uploads'}</h2><button onClick={()=>loadVideos().catch(e=>setMessage(e.message))}>Refresh list</button></div>{videos.length===0?<div className="empty">No videos yet.</div>:<div className="grid">{videos.map(v=><article className={`card ${selected?.id===v.id?'selected':''}`} key={v.id} onClick={()=>openVideo(v)}><div className="video-icon">Play</div><p className={`status ${v.status}`}>{v.status.replace('_',' ')}</p><h3>{v.original_name}</h3><p>{(v.size_bytes/1024/1024).toFixed(1)} MB {v.resolution&&` / ${v.resolution}`}</p>{(user.role==='admin'||v.owner_id===user.id)&&<button className="danger" onClick={e=>{e.stopPropagation();remove(v.id)}}>Delete</button>}</article>)}</div>}</section>{selected&&<section className="detail panel"><div className="section-title"><h2>{selected.original_name}</h2><button onClick={()=>setSelected(null)}>Close</button></div>{!transcript&&<div className="empty">No transcript yet. {canEdit&&<button className="primary" onClick={createTranscript} disabled={busy}>Generate with Whisper</button>}</div>}{transcript?.status==='processing'&&<div className="empty">Whisper is processing. <button onClick={refreshTranscript}>Refresh transcript</button></div>}{transcript?.status==='failed'&&<div className="empty error">Transcription failed: {transcript.error}</div>}{transcript?.status==='ready'&&<><form onSubmit={saveTranscript}><label>Transcript ({transcript.language||'manual'})<textarea name="content" defaultValue={transcript.content} disabled={!canEdit}/></label>{canEdit&&<button className="primary" disabled={busy}>Save transcript</button>}</form><div className="summary-actions">{canEdit&&<><button onClick={()=>createSummary('short')} disabled={busy}>Generate short summary</button><button onClick={()=>createSummary('detailed')} disabled={busy}>Generate detailed summary</button></>}<button onClick={refreshTranscript}>Refresh</button></div><div className="summaries">{summaries.map(s=><article key={s.id}><p className="eyebrow">{s.summary_type} SUMMARY</p><p>{s.content}</p></article>)}</div></>}</section>}</main>;
}
createRoot(document.getElementById('root')).render(<App/>);
